"""add base model

Revision ID: 1529f7de8041
Revises: 484255e78c7d
Create Date: 2023-07-17 22:15:25.117956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1529f7de8041'
down_revision = '484255e78c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
