"""add user model

Revision ID: 4ffe22fd065f
Revises: 1529f7de8041
Create Date: 2023-07-17 22:34:27.050152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffe22fd065f'
down_revision = '1529f7de8041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
