"""add description and date CharityProject

Revision ID: 50a1151dc0b4
Revises: fec844e325b9
Create Date: 2023-07-12 17:12:14.191965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a1151dc0b4'
down_revision = 'fec844e325b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('charityproject', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('charityproject', sa.Column('close_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charityproject', 'close_date')
    op.drop_column('charityproject', 'create_date')
    op.drop_column('charityproject', 'description')
    # ### end Alembic commands ###
